services:
  master:
    image: postgres
    container_name: master
    restart: always
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: db
    volumes:
       - master:/var/lib/postgresql/data/
    networks:
      - bignet
  
  slave:
    image: postgres
    container_name: slave
    restart: always
    environment:
      POSTGRES_USER: slave
      POSTGRES_PASSWORD: slave
    depends_on:
      - master
    networks:
      - bignet

  slave1:
    image: postgres
    container_name: slave1
    restart: always
    environment:
      POSTGRES_USER: slave
      POSTGRES_PASSWORD: slave
    depends_on:
      - master
    networks:
      - bignet  

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - master
    networks:
      - bignet

volumes:
  master:

networks:
  bignet:
    external: true